### PR TITLE
Add German translations

### PR DESCRIPTION
**Pull request by simonua**
Addresses #39 for German (de).

@zkat, Would be good for another native speaker to review, but I think it's probably ~90% accurate ("deutsche Sprache, schwere Sprache") - definitely enough to inform what's meant and what's going on. 

What do you set in an environment to use a locale other than the default?

### CODE REVIEW

**Comment by zkat** [comment]
@simonua `LC_ALL=de npx ...`

**Comment by simonua** [comment]
@zkat, ah, the Unix way. That won't work quite like that on Windows. Will have to check there. Maybe just change the language in the System to see whether/how it affects npx.

**Comment by katemihalikova** [comment]
@simonua It uses [os-locale](http://npm.im/os-locale) under the hood which tries to read env vars before falling back to reading OS config. You can run `set LC_ALL=de` to set/change the env var (for current cmd.exe window only). `npx` will then pick `de` locale up, but OS won't be otherwise affected because it's not a system env var.

**Comment by simonua** [comment]
@katemihalikova @zkat, the things I learn from you. =)

Thank you!

image

**Comment by zkat** [comment]
@simonua unless something strikes me as particularly obvious, I tend to just merge any ok-ish-looking PRs from people who I'm reasonably certain are native speakers. If there's a mistake, I'd rather take what's there and have a different native speaker roll in and fix it later. 👍

**Pull request merged**
