### PR TITLE
fix(windows): escape prefix path on windows

### LINKED ISSUE #100: Error: EPERM: operation not permitted, mkdir 'C:\Users\Foo'
**Environment**: Windows 10
**npx Version**: 9.4.1
**See also**: #84 

**Reason**:
My user home directory contain whitespace, like `foo bar`

### PR DESCRIPTION
**Pull request by brianpeiris**
Closes #100

### CODE REVIEW

**Comment by brianpeiris** [comment]
`escapeArgs` `asPath` wouldn't have worked here. npm wants the whole path quoted on windows.

**Comment by brianpeiris** [comment]
Hmm. Not sure why some tests timed out on travis. Will look into it later.

Also interesting to note that the test suite was failing on my windows machine, since my user directory has a space in it. Appveyor's user does not have any spaces. The test suite passes on my machine with this fix.

**Comment by zkat** [comment]
@brianpeiris This project was relicensed to ISC (from CC0-1.0) since you put up this PR. Are you ok with me merging this under that license instead?

**Comment by brianpeiris** [comment]
Yup, fine with me.

**Comment by Pamelapelkola** [comment]
Is there any update on this issue? I cannot use npm on my machine because of it.

**Comment by zkat** [comment]
cc @noahleigh does this seem alright to you?

**Comment by noelleleigh** [comment]
@zkat It works for me.
My only question is whether it would be better to use `child.escapeArg` rather than manual quoting, since that function seems to be purpose-built for this kind of scenario (with platform-specific conditions built-in)?

**Comment by zkat** [comment]
Closing this in favor of #181 (which includes @brianpeiris' commit)

**Pull request closed without merging**
